import { Component } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { HubSpeedDialComponent } from '../speed-dial/speed-dial.component';
import { HubFabComponent } from './fab.component';

/**
 * `<hub-fab>` is the one component of this library that stays outside emulated encapsulation,
 * and the reason is written above its `encapsulation:` line. These tests are what make that
 * reason reviewable: they fail the day the exception stops being needed — or the day someone
 * removes it without dealing with what it was holding up.
 */

/** One `selector { … }` rule of the stylesheet as the build injects it into the document. */
interface StyleRule {
	selector: string;
	body: string;
}

function shippedRules(): StyleRule[] {
	const css = Array.from(document.querySelectorAll('style'))
		.map((style) => style.textContent ?? '')
		.filter((text) => text.includes('hub-fab'))
		.join('\n')
		.replace(/\/\*[\s\S]*?\*\//g, '');

	const rules: StyleRule[] = [];
	for (const match of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
		rules.push({ selector: match[1].trim(), body: match[2] });
	}
	return rules;
}

@Component({
	imports: [HubFabComponent, HubSpeedDialComponent],
	template: `
		<hub-fab color="primary"><span slot="icon">+</span></hub-fab>
		<hub-speed-dial color="primary"><span hubTrigger>+</span></hub-speed-dial>
	`
})
class FabHostComponent {}

describe('the hub-fab stylesheet exception', () => {
	beforeEach(async () => {
		await TestBed.configureTestingModule({ imports: [FabHostComponent] }).compileComponents();
		const fixture = TestBed.createComponent(FabHostComponent);
		document.body.appendChild(fixture.nativeElement);
		fixture.detectChanges();
	});

	/**
	 * Reason (3). `HubSpeedDialComponent` renders its trigger as a plain `<button class="hub-fab">`
	 * inside its OWN template, so that button carries the speed dial's content marker and never
	 * the FAB's. Scoping this sheet would leave it round, shadowless and unpositioned.
	 */
	it('dresses the speed dial trigger, which lives in another component view', () => {
		const trigger = document.querySelector('hub-speed-dial button.hub-fab') as HTMLElement;
		expect(trigger).toBeTruthy();

		const fabMarker = Array.from(document.querySelector('hub-fab')!.attributes)
			.map((attribute) => attribute.name)
			.find((name) => name.startsWith('_nghost-'));
		// The trigger carries no marker of the FAB's, so only an unscoped rule can reach it.
		expect(fabMarker ? trigger.hasAttribute(fabMarker.replace('_nghost-', '_ngcontent-')) : false).toBe(false);

		const base = shippedRules().find((rule) => rule.selector === '.hub-fab');
		expect(base).toBeTruthy();
		expect(base!.body).toContain('box-shadow');
	});

	/**
	 * Reason (2). The six built-in colours are generated by `hub-fab-color()`, the very mixin
	 * `ng-hub-ui-buttons/styles` exports so a consumer can register their own accent from a
	 * global sheet. Both halves have to land on the identical plain `.hub-fab-<type>` selector,
	 * or a consumer's colour would be out-specified by every built-in.
	 */
	it('emits the built-in colours on the same plain selector the public mixin does', () => {
		const builtIn = shippedRules().filter((rule) =>
			/^\.hub-fab-(primary|secondary|success|danger|warning|info)$/.test(rule.selector)
		);

		expect(builtIn.length).toBe(6);
		for (const rule of builtIn) {
			expect(rule.body).toContain('background:');
		}
	});

	/**
	 * The price of the exception, and the part that keeps it honest: a global sheet may only
	 * carry selectors the library owns. Nothing here may match an element outside the FAB
	 * family — no bare element selectors, no utility-class names.
	 */
	it('namespaces every selector it publishes under the library own classes', () => {
		const parts = shippedRules()
			.map((rule) => rule.selector)
			.flatMap((selector) => selector.split(','))
			.map((part) => part.trim())
			.filter((part) => part.length > 0);

		// Anything that is not a class, a pseudo-class or a descendant combinator would be a
		// selector that can match an element the library does not own.
		const notOnlyClasses = parts.filter((part) => !/^[.:\w\s()-]*$/.test(part) || /(^|[\s>+~(])[a-z]/.test(part));
		expect(notOnlyClasses).toEqual([]);

		const classes = [...new Set(parts.flatMap((part) => [...part.matchAll(/\.([\w-]+)/g)].map((match) => match[1])))];
		expect(classes.length).toBeGreaterThan(0);
		for (const name of classes) {
			expect(name.startsWith('hub-fab') || name.startsWith('hub-speed-dial')).toBe(true);
		}
	});
});
